CREATE TABLE recipe (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nev TEXT NOT NULL,
  kep TEXT NOT NULL,
  leiras TEXT NOT NULL,
  hozzavalok TEXT NOT NULL,
  keszitesi_utmutato TEXT NOT NULL,
  elokeszitesi_ido TEXT NOT NULL,
  sutesi_ido TEXT NOT NULL,
  adagok_szama TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

INSERT INTO recipe (id, nev, kep, leiras, hozzavalok, keszitesi_utmutato, elokeszitesi_ido, sutesi_ido, adagok_szama, created_at, updated_at) VALUES
(1, 'Csokoládés Brownie', 'brownie.jpg', 'Egy gazdag és szaftos csokoládés sütemény, amely tökéletesen olvad a szádban.', '200 g étcsokoládé, 150 g vaj, 200 g cukor, 3 tojás, 100 g liszt, 1 teáskanál vanília kivonat, Egy csipet só', 'Melegítsd elő a sütőt 180°C-ra. Vajazz ki egy 20x20 cm-es tepsit. Olvaszd fel a csokoládét és a vajat egy tálban gőz fölött, majd hagyd kicsit hűlni. Keverd hozzá a cukrot, majd egyesével a tojásokat, jól elkeverve minden hozzáadás után. Add hozzá a vanília kivonatot és a csipet sót. Szitáld hozzá a lisztet, és óvatosan keverd össze, amíg egységes tésztát nem kapsz. Öntsd a tésztát a kivajazott tepsibe, és süsd 25-30 percig. Hagyd teljesen kihűlni, majd szeleteld.', '15 perc', '25-30 perc', '12 szelet', '2024-06-07 21:07:48', '2025-06-18 14:03:51'),
(2, 'Almás Pite', 'almaspite.jpg', 'Frissen sült omlós tészta, lédús almás töltelékkel.', '250 g liszt, 150 g vaj, 100 g cukor, 1 tojás, 1 teáskanál sütőpor, 4-5 alma, 2 evőkanál fahéj, 2 evőkanál citromlé', 'Melegítsd elő a sütőt 180°C-ra. Vajazz ki egy piteformát. Keverd össze a lisztet, vajat, cukrot, tojást és sütőport, amíg sima tésztát nem kapsz. Csomagold be a tésztát fóliába, és tedd hűtőbe 30 percre. Hámozd meg és szeleteld fel az almákat, majd keverd össze fahéjjal és citromlével. Nyújtsd ki a tésztát, és helyezd a piteformába. Terítsd rá az almás keveréket, majd fedd be a maradék tésztával (például rácsozva). Süsd 40-45 percig, amíg aranybarna nem lesz. Hagyd kihűlni szeletelés előtt.', '30 perc', '40-45 perc', '8 szelet', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(3, 'Citromos Mákos Muffin', 'citromosmakos.jpg', 'Frissítő citrom és ropogós mák kombinációja, amely tökéletes reggeli vagy uzsonna. Gyorsan elkészíthető és rendkívül ízletes.', '200 g liszt, 150 g cukor, 2 tojás, 100 ml tej, 100 ml olaj, 2 evőkanál mák, 1 teáskanál sütőpor, 1 citrom reszelt héja és leve', 'Melegítsd elő a sütőt 180°C-ra. Készíts elő 12 muffinformát papír kapszlikkal. Keverd össze a lisztet, cukrot, mákot és sütőport egy nagy tálban. Egy másik tálban keverd össze a tojásokat, tejet, olajat, citromhéjat és citromlevet. Öntsd a nedves hozzávalókat a száraz hozzávalókhoz, és keverd össze, amíg egységes tésztát nem kapsz. Töltsd meg a muffinformákat a tésztával, körülbelül háromnegyedig. Süsd 20-25 percig, amíg aranybarnák nem lesznek és a tetejük rugalmas. Hagyd hűlni.', '15 perc', '20-25 perc', '12 muffin', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(4, 'Sárgarépás Torta', 'repatorta.jpg', 'Egy egészségesebb alternatíva, amely tele van ízzel. A szaftos sárgarépa és a fűszeres tészta egyesül ebben az ínycsiklandó süteményben.', '300 g sárgarépa (reszelt), 200 g liszt, 150 g cukor, 150 ml olaj, 3 tojás, 1 teáskanál fahéj, 1 teáskanál szódabikarbóna, 1 teáskanál sütőpor, Egy csipet só', 'Melegítsd elő a sütőt 180°C-ra. Vajazz ki és lisztezz meg egy 24 cm-es tortaformát. Reszeld le a sárgarépát finomra. Keverd össze a lisztet, cukrot, fahéjat, szódabikarbónát, sütőport és sót egy nagy tálban. Egy másik tálban keverd össze a tojásokat és az olajat. Add hozzá a nedves hozzávalókat a száraz hozzávalókhoz, majd keverd bele a reszelt sárgarépát. Öntsd a tésztát a tortaformába, és süsd 40-45 percig, amíg tűpróbánál tiszta marad a tű. Hagyd kihűlni.', '20 perc', '40-45 perc', '8 szelet', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(5, 'Málnás Sajttorta', 'malnassajttorta.jpeg', 'Egy krémes és lágy sajttorta, amelyet friss málna tesz még finomabbá. Készítsd el ezt az elegáns desszertet egy különleges alkalomra!', '200 g kekszmorzsa, 100 g vaj (olvasztott), 500 g krémsajt, 200 g cukor, 3 tojás, 200 g málna, 1 teáskanál vanília kivonat', 'Melegítsd elő a sütőt 160°C-ra. Készíts elő egy 24 cm-es tortaformát sütőpapírral. Keverd össze a kekszmorzsát és az olvasztott vajat, majd nyomkodd egyenletesen a tortaforma aljába. Egy nagy tálban keverd simára a krémsajtot és a cukrot. Egyesével add hozzá a tojásokat, mindegyiket jól elkeverve. Add hozzá a vanília kivonatot és keverd el. Öntsd a krémsajtos keveréket a kekszalapra, és szórd meg málnával. Süsd 50-60 percig, amíg a közepén már csak enyhén remeg. Hagyd teljesen kihűlni, majd tedd hűtőbe legalább 2 órára.', '20 perc', '50-60 perc', '8 szelet', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(6, 'Kókuszgolyó', 'kokuszgolyo.jpg', 'Kókuszos és kakaós finomság, amit nem kell sütni. Gyors és egyszerű recept, amely mindig nagy sikert arat.', '200 g darált keksz, 100 g porcukor, 2 evőkanál kakaópor, 100 g vaj (olvasztott), 100 ml tej, 100 g kókuszreszelék', 'Egy nagy tálban keverd össze a darált kekszet, porcukrot és kakaóport. Add hozzá az olvasztott vajat és a tejet, majd gyúrj belőle egységes masszát. Nedves kézzel formázz kis golyókat a masszából. Forgasd meg a golyókat a kókuszreszelékben. Tedd hűtőbe legalább egy órára, hogy megdermedjenek.', '15 perc', '-', '20 golyó', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(7, 'Tiramisu', 'tiramisu.jpg', 'Az olasz klasszikus, amely kávéval és mascarponéval készül. Ez a könnyű és ízletes desszert biztosan a kedvenced lesz!', '250 g mascarpone, 200 ml habtejszín, 100 g cukor, 200 ml kávé (kihűlt), 2 evőkanál kakaópor, 1 csomag babapiskóta', 'Főzd le a kávét, majd hagyd kihűlni. Egy tálban keverd simára a mascarponét a cukorral. Verd fel a habtejszínt kemény habbá, majd óvatosan keverd a mascarponéhoz. Mártsd a babapiskótákat a kihűlt kávéba, majd rétegezd őket egy tálba. Terítsd a krémet a piskótákra, és ismételd a rétegezést, amíg a hozzávalók elfogynak. Szórd meg a tetejét kakaóporral, majd tedd hűtőbe legalább 2 órára, hogy összeérjenek az ízek.', '20 perc', '-', '8 adag', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(8, 'Epres Piskóta', 'eprespiskota.jpg', 'Puha és könnyű piskóta, édes eperrel megbolondítva. Egy egyszerű, de lenyűgöző sütemény, amely bármilyen alkalomra tökéletes.', '4 tojás, 200 g cukor, 200 g liszt, 1 teáskanál sütőpor, 200 g eper (szeletelt), 100 ml tejszín (felvert)', 'Melegítsd elő a sütőt 180°C-ra. Vajazz ki egy 24 cm-es tortaformát. Verd fel a tojásokat és a cukrot habosra és világosra. Keverd hozzá a lisztet és a sütőport, óvatosan összeforgatva, hogy ne törjön össze a hab. Öntsd a tésztát a kivajazott formába, és süsd 20-25 percig, amíg aranybarna nem lesz és a tűpróba tiszta marad. Hagyd teljesen kihűlni, majd vágd félbe. Kend meg az alsó felét tejszínhabbal, és terítsd rá a szeletelt epreket. Tedd rá a piskóta tetejét, és díszítsd tejszínhabbal és eperrel.', '15 perc', '20-25 perc', '8 szelet', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(9, 'Nutellás Keksz', 'nutellaskeksz.jpeg', 'Ezek a kekszek ropogósak kívül és lágyak belül, tele finom Nutellával. Egy édes kényeztetés, amit imádni fogsz!', '200 g Nutella, 100 g cukor, 1 tojás, 150 g liszt, 1 teáskanál sütőpor', 'Melegítsd elő a sütőt 180°C-ra. Bélelj ki egy tepsit sütőpapírral. Egy tálban keverd össze a Nutellát, cukrot és tojást, amíg sima nem lesz. Add hozzá a lisztet és a sütőport, és keverd össze, amíg tésztává áll össze. Formázz golyókat a tésztából, majd lapítsd el őket a tepsiben. Süsd 10-12 percig, amíg a kekszek szélei ropogósak lesznek. Hagyd hűlni, majd tálald.', '10 perc', '10-12 perc', '24 keksz', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(10, 'Fahéjas Csiga', 'fahejascsiga.jpg', 'Illatos és puha fahéjas csiga, amely tökéletes a hideg napokra. Frissen sült, melegen a legfinomabb!', '500 g liszt, 250 ml tej, 100 g cukor, 100 g vaj (olvasztott), 2 tojás, 1 csomag élesztő, 2 evőkanál fahéj, 50 g barna cukor', 'Melegítsd fel a tejet langyosra, majd keverd bele az élesztőt és a cukrot, hagyd felfutni 10 percig. Egy nagy tálban keverd össze a lisztet, olvasztott vajat és tojásokat, majd add hozzá az élesztős keveréket. Gyúrj belőle sima tésztát. Tedd a tésztát egy enyhén lisztezett felületre, és hagyd kelni 1 órán át, amíg duplájára nő. Nyújtsd ki a tésztát téglalap alakúra, szórd meg fahéjjal és barna cukorral, majd tekerd fel szorosan. Szeleteld fel a tekercset 2 cm vastag szeletekre, és helyezd őket kivajazott tepsibe. Süsd 180°C-on 20-25 percig, amíg aranybarnák nem lesznek. Hagyd hűlni, majd tálald.', '20 perc + 1 óra kelesztés', '20-25 perc', '12 csiga', '2024-06-07 21:07:48', '2024-06-07 21:07:48'),
(11, 'Sacher torta', 'sacher.jpg', 'Egy klasszikus osztrák desszert, amely gazdag csokoládés tészta és sárgabarack lekvár tölti meg, majd csokoládé bevonattal borítom. Elegáns és ízletes választás ünnepi alkalmakra vagy különleges eseményekre.', '150 g étcsokoládé, 150 g vaj, 150 g cukor, 6 tojás (szétválasztva), 150 g liszt, 200 g sárgabarack lekvár, 200 g étcsokoládé bevonat, 1 teáskanál vanília kivonat, Egy csipet só', 'Melegítsd elő a sütőt 170°C-ra. Vajazz ki és lisztezz meg egy 23 cm-es tortaformát. Olvaszd fel a csokoládét gőz fölött, majd hagyd kicsit hűlni. Keverd habosra a vajat és a cukrot egy nagy tálban. Add hozzá a tojássárgákat egyesével, minden tojássárgát alaposan elkeverve. Add hozzá az olvasztott csokoládét és a vanília kivonatot, majd keverd simára. Szitáld hozzá a lisztet, és óvatosan keverd össze a tésztát. Verd fel a tojásfehérjéket egy csipet sóval kemény habbá, majd óvatosan forgasd bele a csokoládés masszába, ügyelve arra, hogy a hab ne törjön össze. Öntsd a tésztát az előkészített tortaformába, és süsd 50-60 percig, amíg a közepébe szúrt tű tisztán jön ki. Hagyd a tortát teljesen kihűlni a formában, majd vágd ketté vízszintesen egy éles késsel. Kend meg a torta alsó rétegét és a tetejét sárgabarack lekvárral. Olvaszd fel az étcsokoládé bevonatot, és öntsd a torta tetejére, egyenletesen eloszlatva és hagyva, hogy az oldalakra is lefolyjon. Hagyd a csokoládébevonatot megdermedni, majd szeleteld fel és tálald. Jó étvágyat!', '15 perc', '55 perc', '12 szelet', '2024-06-08 15:28:32', '2025-06-19 01:06:02');

CREATE TABLE user2 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userName TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  type TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

INSERT INTO user2 (id, userName, email, password, type, created_at, updated_at) VALUES
(1, 'aaa', 'aaa@gmail.com', '7b0fba53557854d7e61667bab1df81aa4effb879', 'user', '2025-06-17 10:01:56', '2025-06-17 10:01:56'),
(2, 'Admin1', 'admin@gmail.com', '6c7ca345f63f835cb353ff15bd6c5e052ec08e7a', 'admin', '2025-06-17 10:01:56', '2025-06-17 10:01:56'),
(3, 'Admin2', 'admin2@gmail.com', '315f166c5aca63a157f7d41007675cb44a948b33', 'admin', '2025-06-18 06:47:46', '2025-06-18 06:47:46'),
(4, 'bbb', 'bbb@gmail.com', '6be712a6e73d979726c02a308b3457f9f5cf148e', 'user', '2025-06-18 07:36:15', '2025-06-18 07:36:15'),
(5, 'Anna', 'admin3@gmail.com', '0dc3c11cd09782f5404591efc3631994065a774d', 'admin', '2025-06-18 07:37:01', '2025-06-18 07:37:01'),
(6, 'suti', 'suti@gmail.com', '30d2e2cb9cda48e09e2a757f2084040dc22833fc', 'user', '2025-06-18 15:07:26', '2025-06-18 15:07:26'),
(7, 'Juli', 'juli@gmail.com', '0a834e13ab9c560fd87f370113641924689b883c', 'user', '2025-06-18 22:17:43', '2025-06-18 22:17:43'),
(8, 'Tomi', 'tomi@gmail.com', '1c3f704cb51e403ca868437e82c98b13fd6cbd4a', 'user', '2025-06-18 22:35:14', '2025-06-18 22:35:14');